const AllToursData = [
  {
    id: 1,
    name: "Alpine Hiking & Climbing Experience",
    price: "$ 2600",
    location: "Switzerland",
    days: "7",
    people : "10",
    score: 9.4,
    imageAdd: "/images/tours/david-magalhaes-lgdH8f69_JQ-unsplash.jpg",
  },
  {
    id: 2,
    name: "Luxury City Tour of Paris",
    price: "$ 3200",
    location: "France",
    days: "5",
    people : "14",
    score: 9.5,
    imageAdd: "/images/tours/kiarash-mansouri-lPYbaH6jsBw-unsplash.jpg",
  },
  {
    id: 3,
    name: "Romantic Venice & Rome Adventure",
    price: "$ 2800",
    location: "Italy",
    days: "6",
    people : "5",
    score: 9.0,
    imageAdd: "/images/tours/pexels-jan-tang-598592438-19471035.jpg", // پیشنهاد تصویر: کانال‌های ونیز یا کولوسئوم
  },
  {
    id: 4,
    name: "Ancient Wonders of Athens",
    price: "$ 1400",
    location: "Greece",
    days: "4",
    people : "9",
    score: 8.3,
    imageAdd: "/images/tours/pexels-sakuratosoju-29894258.jpg",
  },
  {
    id: 5,
    name: "Tropical Escape to Bali Beaches",
    price: "$ 1850",
    location: "Indonesia",
    days: "6",
    people : "13",
    score: 8.7,
    imageAdd: "/images/tours/pexels-pok-rie-33563-321474.jpg",
  },
  {
    id: 6,
    name: "Wild Safari Adventure in Kenya",
    price: "$ 2100",
    location: "Kenya",
    days: "7",
    people : "25",
    score: 9.2,
    imageAdd: "/images/tours/david-clode-YV_WwNH09cI-unsplash.jpg",
  },
  {
    id: 7,
    name: "Amazon Jungle Expedition",
    price: "$ 2400",
    location: "Brazil",
    days: "8",
    people : "20",
    score: 9.1,
    imageAdd: "/images/tours/ivars-utinans-vkQgb1lZZPQ-unsplash.jpg",
  },
  {
    id: 8,
    name: "Cultural Journey Through Kyoto",
    price: "$ 2300",
    location: "Japan",
    days: "6",
    people : "18",
    score: 9.1,
    imageAdd: "/images/tours/james-pere-KGf-6WoIb3M-unsplash.jpg",
  },
  {
    id: 9,
    name: "Desert Nights in Magical Morocco",
    price: "$ 1700",
    location: "Morocco",
    days: "5",
    people : "16",
    score: 8.9,
    imageAdd: "/images/tours/manav-jain-KomOjNU97bY-unsplash.jpg",
  },
  {
    id: 10,
    name: "Sunny Days in Barcelona & Madrid",
    price: "$ 2500",
    location: "Spain",
    days: "6",
    people : "3",
    score: 9.0,
    imageAdd: "/images/tours/pexels-ken-cheung-3355734-32868875.jpg",
  },
  {
    id: 11,
    name: "Classic Rome & Vatican Tour",
    price: "$ 2900",
    location: "Italy",
    days: "5",
    people : "7",
    score: 9.1,
    imageAdd: "/images/tours/pexels-kelly-1179532-19143253.jpg", 
  },
  {
    id: 12,
    name: "Carnival & Culture in Rio de Janeiro",
    price: "$ 2800",
    location: "Brazil",
    days: "6",
    people : "6",
    score: 9.0,
    imageAdd: "/images/tours/pexels-luan-goncalves-1264152-13911606.jpg", 
  },
  {
    id: 13,
    name: "Santorini Sunset & Sea Tour",
    price: "$ 2600",
    location: "Greece",
    days: "5",
    people : "8",
    score: 9.3,
    imageAdd: "/images/tours/pexels-ujjwal-kishore-11047820.jpg", 
  },
  {
    id: 14,
    name: "Amalfi Coast Luxury Escape",
    price: "$ 3300",
    location: "Italy",
    days: "5",
    people : "10",
    score: 9.4,
    imageAdd: "/images/tours/pexels-frans-van-heerden-201846-632522.jpg", 
  },
  {
    id: 15,
    name: "Alpine Hiking & Climbing Experience",
    price: "$ 3500",
    location: "Switzerland",
    days: "6",
    people : "12",
    score: 9.2,
    imageAdd: "/images/tours/pexels-yaroslav-shuraev-7041568.jpg", 
  },
  {
    id: 16,
    name: "Modern Tokyo & Tradition Tour",
    price: "$ 3200",
    location: "Japan",
    days: "5",
    people : "2",
    score: 9.1,
    imageAdd: "/images/tours/pexels-tonywuphotography-21792360.jpg", 
  }
];

export default AllToursData;
